---

# Playbook Name: Configure Vagrant Virtual Machines
# Purpose:
#   This playbook configures network interfaces, sets routing priorities,
#   and sends a login request to a web portal for each VM in the inventory group "VMs".
# Author: Felipe Campanaro
# Date: 2025-08-15
# Notes:
#   - Requires Ansible to be run with 'become' privileges
#   - Assumes interface names are enp0s8 (secondary) and enp0s3 (primary)
#   - IP addresses and metrics are hardcoded for a lab environment
#   
# Usage:
#   ansible-playbook vms.yml

- name: Configure Vagrant Virtual Machines
  hosts: VMs
  become: yes

  # User credentials mapped per VM hostname
  vars:
    users:
      client21: { username: "BR-MAC-USER21", password: "1365" }
      client22: { username: "BR-MAC-USER22", password: "6015" }
      client23: { username: "BR-MAC-USER23", password: "1451" }
      client24: { username: "BR-MAC-USER24", password: "8756" }
      client25: { username: "BR-MAC-USER25", password: "6642" }
      client26: { username: "BR-MAC-USER26", password: "7005" }
      client27: { username: "BR-MAC-USER27", password: "6583" }
      client28: { username: "BR-MAC-USER28", password: "2381" }
      client29: { username: "BR-MAC-USER29", password: "7656" }
      client30: { username: "BR-MAC-USER30", password: "7260" }
      client31: { username: "BR-MAC-USER31", password: "2703" }
      client32: { username: "BR-MAC-USER32", password: "1200" }
      client33: { username: "BR-MAC-USER33", password: "7640" }
      client34: { username: "BR-MAC-USER34", password: "6443" }
      client35: { username: "BR-MAC-USER35", password: "2168" }
      client36: { username: "BR-MAC-USER36", password: "6754" }
      client37: { username: "BR-MAC-USER37", password: "6333" }
      client38: { username: "BR-MAC-USER38", password: "4625" }
      client39: { username: "BR-MAC-USER39", password: "7352" }
      client40: { username: "BR-MAC-USER40", password: "1840" }
      client41: { username: "BR-MAC-USER41", password: "3146" }
      client42: { username: "BR-MAC-USER42", password: "3117" }
      client43: { username: "BR-MAC-USER43", password: "7404" }
      client44: { username: "BR-MAC-USER44", password: "6385" }
      client45: { username: "BR-MAC-USER45", password: "7205" }
      client46: { username: "BR-MAC-USER46", password: "7878" }
      client47: { username: "BR-MAC-USER47", password: "3144" }
      client48: { username: "BR-MAC-USER48", password: "4421" }
      client49: { username: "BR-MAC-USER49", password: "8436" }
      client50: { username: "BR-MAC-USER50", password: "5154" }
      
  tasks:
    # 1. Enable secondary network interface (enp0s8)
    - name: Bring up enp0s8
      command: ip link set dev enp0s8
    
    # 2. Set default route via enp0s8 with higher priority (metric 100)
    - name: Set priority for 172.20.0.1 via enp0s8
      command: ip route change default via 172.20.0.1 dev enp0s8 metric 100

    # 3. Set backup default route via enp0s3 with lower priority (metric 200)
    - name: Set priority for 10.0.2.2 via enp0s3
      command: ip route replace default via 10.0.2.2 dev enp0s3 metric 200
    
    # 4. Send HTTP POST login request to portal
    # This uses VM-specific credentials from the 'users' variable
    - name: Send login request with curl
      shell: |
        curl -d "username={{ users[inventory_hostname].username }}&password={{ users[inventory_hostname].password }}" \
             -X POST http://launch.speedcast.com/login
